// Maps component type → HTML tag + class
const COMP_MAP = {
  navbar:    (c) => `  <nav class="bx-navbar">${c.properties?.text || "Navigation"}</nav>`,
  hero:      (c) => `  <section class="bx-hero"><h1>${c.properties?.text || c.properties?.content || "Hero Title"}</h1></section>`,
  header:    (c) => `  <header class="bx-header"><h2>${c.properties?.text || c.properties?.content || "Header"}</h2></header>`,
  button:    (c) => `  <button class="bx-button">${c.properties?.text || "Button"}</button>`,
  text:      (c) => `  <p class="bx-text">${c.properties?.text || c.properties?.content || "Text block"}</p>`,
  image:     (c) => `  <img class="bx-image" src="${c.properties?.src || ""}" alt="${c.properties?.alt || "Image"}" />`,
  card:      (c) => `  <div class="bx-card"><h3>${c.properties?.text || c.properties?.title || "Card Title"}</h3><p>Card content goes here.</p></div>`,
  container: (c) => `  <div class="bx-container">${c.properties?.text || ""}</div>`,
  footer:    (c) => `  <footer class="bx-footer">${c.properties?.text || "Footer"}</footer>`,
};

export function generateHTML(project) {
  const bodyLines = (project.components || []).map((c) => {
    const fn = COMP_MAP[c.type];
    return fn ? fn(c) : `  <div class="bx-${c.type}">${JSON.stringify(c.properties)}</div>`;
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${project.name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>

${bodyLines.join("\n\n")}

</body>
</html>
`;
}

export function generateCSS(project) {
  return `/* Generated by BuildX — ${project.name} */

*, *::before, *::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  background: #ffffff;
  color: #1a1a1a;
  line-height: 1.6;
}

/* Navbar */
.bx-navbar {
  width: 100%;
  padding: 16px 32px;
  background: #1e1b4b;
  color: #ffffff;
  font-size: 16px;
  font-weight: 600;
  letter-spacing: 0.3px;
}

/* Hero */
.bx-hero {
  width: 100%;
  padding: 80px 32px;
  text-align: center;
  background: #f8fafc;
}

.bx-hero h1 {
  font-size: 48px;
  font-weight: 800;
  color: #0f172a;
  letter-spacing: -1px;
  line-height: 1.15;
}

/* Header */
.bx-header {
  padding: 40px 32px 20px;
  text-align: center;
}

.bx-header h2 {
  font-size: 32px;
  font-weight: 700;
  color: #0f172a;
}

/* Button */
.bx-button {
  display: inline-block;
  margin: 16px 32px;
  padding: 14px 36px;
  background: #6366f1;
  color: #ffffff;
  font-size: 15px;
  font-weight: 600;
  border: none;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.2s;
}

.bx-button:hover {
  background: #4f46e5;
}

/* Text / Paragraph */
.bx-text {
  max-width: 680px;
  margin: 16px auto;
  padding: 0 32px;
  font-size: 17px;
  color: #475569;
  line-height: 1.75;
}

/* Image */
.bx-image {
  display: block;
  max-width: 100%;
  height: auto;
  margin: 24px auto;
  border-radius: 10px;
}

/* Card */
.bx-card {
  max-width: 360px;
  margin: 20px auto;
  padding: 28px;
  background: #f8fafc;
  border: 1px solid #e2e8f0;
  border-radius: 12px;
}

.bx-card h3 {
  font-size: 20px;
  font-weight: 700;
  color: #0f172a;
  margin-bottom: 10px;
}

.bx-card p {
  font-size: 15px;
  color: #64748b;
}

/* Container */
.bx-container {
  max-width: 960px;
  margin: 0 auto;
  padding: 24px 32px;
}

/* Footer */
.bx-footer {
  width: 100%;
  padding: 24px 32px;
  background: #0f172a;
  color: #94a3b8;
  font-size: 14px;
  text-align: center;
  margin-top: 60px;
}

/* Responsive */
@media (max-width: 640px) {
  .bx-hero h1 { font-size: 32px; }
  .bx-header h2 { font-size: 24px; }
  .bx-button { width: calc(100% - 64px); text-align: center; }
}
`;
}
